# Vesper theme for Starship prompt (Dark to Light gradient)
# Main format for the prompt
format = """
[](fg:#101010 bg:#101010)\
[](fg:#101010 bg:#101010)\
$username\
[](fg:#101010 bg:#161616)\
[](fg:#161616 bg:#1C1C1C)\
$directory\
[](fg:#1C1C1C bg:#232323)\
$git_branch\
$git_status\
[](fg:#232323 bg:#282828)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#282828 bg:#343434)\
$time\
[](fg:#343434)
$character"""
# Disable the blank line at the start of the prompt
add_newline = false
[character]
success_symbol = "[](fg:#343434)"
error_symbol = "[](fg:#FF8080)" # Red for error
format = "$symbol"
# Username module with a neat symbol
[username]
show_always = true
style_user = "fg:#FFC799 bg:#101010"
style_root = "fg:#FF8080 bg:#101010"  # Red for root
format = '[ abdelilah ]($style)'
disabled = false
# Directory module with improved truncation and icons
[directory]
style = "fg:#99FFE4 bg:#1C1C1C"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
# Directory substitutions for common folders
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = "󰈔 "
"Work" = "󰑨 "
# Git branch and status modules
[git_branch]
symbol = " "
style = "fg:#FFC799 bg:#232323"
format = '[ $symbol $branch ]($style)'
[git_status]
style = "fg:#FFC799 bg:#232323"
format = '[$all_status$ahead_behind ]($style)'
# Programming language modules with consistent styling
[c]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[elixir]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[elm]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[golang]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[gradle]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[haskell]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[java]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[julia]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[nodejs]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[nim]
symbol = "󰆥 "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[rust]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
[scala]
symbol = " "
style = "fg:#99FFE4 bg:#282828"
format = '[ $symbol ($version) ]($style)'
# Time module
[time]
disabled = false
time_format = "%R"
style = "fg:#FFC799 bg:#343434"  # Lighter time background
format = '[ 󰥔 $time ]($style)'
# Additional modules
[aws]
symbol = " "
style = "fg:#FFFFFF bg:#232323"
format = '[ $symbol $profile ]($style)'
[docker_context]
symbol = " "
style = "fg:#FFFFFF bg:#232323"
format = '[ $symbol $context ]($style)'
[python]
symbol = " "
style = "fg:#FFFFFF bg:#232323"
format = '[ $symbol ($version) ]($style)'
[ruby]
symbol = " "
style = "fg:#FFFFFF bg:#232323"
format = '[ $symbol ($version) ]($style)'
# Memory usage module
[memory_usage]
symbol = "󰍛 "
style = "fg:#99FFE4 bg:#232323"
format = '[ $symbol $ram ]($style)'
# Custom OS symbols
[os.symbols]
Alpine = " "
Arch = " "
Debian = " "
Fedora = " "
Macos = " "
Ubuntu = " "
Windows = "󰍲 "
