# Aura theme for Starship prompt
# Main format for the prompt
format = """
[](fg:#FFFFFF bg:#86d0f9)\
[](fg:#86d0f9 bg:#86d0f9)\
$username\
[](fg:#86d0f9 bg:#ae9ad6)\
[](fg:#ae9ad6 bg:#6d6883)\
$directory\
[](fg:#6d6883 bg:#15141b)\
$git_branch\
$git_status\
[](fg:#15141b bg:#1c1b24)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#1c1b24 bg:#21202e)\
$time\
[](fg:#21202e)
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[](fg:#21202e)"
error_symbol = "[](fg:#e26c7c)" # Red for error
format = "$symbol"

# Username module with a neat symbol
[username]
show_always = true
style_user = "bg:#86d0f9"
style_root = "bg:#ae9ad6"  # Purple for root
format = '[ abdelilah ]($style)'
disabled = false

# Directory module with improved truncation and icons
[directory]
style = "bg:#6d6883"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Directory substitutions for common folders
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = "󰈔 "
"Work" = "󰑨 "

# Git branch and status modules
[git_branch]
symbol = " "
style = "fg:#a277ff bg:#15141b"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#a277ff bg:#15141b"
format = '[$all_status$ahead_behind ]($style)'

# Programming language modules with consistent styling
[c]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#86d0f9 bg:#1c1b24"
format = '[ $symbol ($version) ]($style)'

# Time module
[time]
disabled = false
time_format = "%R"
style = "fg:#86d0f9 bg:#21202e"  # Darker time background
format = '[ 󰥔 $time ]($style)'

# Additional modules
[aws]
symbol = " "
style = "bg:#15141b"
format = '[ $symbol $profile ]($style)'

[docker_context]
symbol = " "
style = "bg:#15141b"
format = '[ $symbol $context ]($style)'

[python]
symbol = " "
style = "bg:#86d0f9"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = " "
style = "bg:#ae9ad6"
format = '[ $symbol ($version) ]($style)'

# Memory usage module
[memory_usage]
symbol = "󰍛 "
style = "bg:#15141b"
format = '[ $symbol $ram ]($style)'

# Custom OS symbols
[os.symbols]
Alpine = " "
Arch = " "
Debian = " "
Fedora = " "
Macos = " "
Ubuntu = " "
Windows = "󰍲 "
